name: Build Flatpak

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: Build Flatpak Package
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Flatpak bundle
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: halftone.flatpak
          manifest-path: be.alexandervanhee.gradia.json
          cache-key: flatpak-builder-${{ github.sha }}
